### ISSUE TITLE
 [ERROR] [rwanda.alaveteli.org] public_body#list (I18n::MissingInterpolationArgument) "missing interpolation argument..."

### ISSUE THREAD

**Issue by gbp** [mysociety/sobanukirwa-theme#92]
```
An I18n::MissingInterpolationArgument occurred in public_body#list:

  missing interpolation argument "first_letter" in {:count=>1} ("Habonetse {{count}} ibigo bya leta bitangirwa na‘{{first_letter}}’" given)
  lib/i18n_fixes.rb:35:in `block in gettext_interpolate'


-------------------------------
Request:
-------------------------------

  * URL        : https://sobanukirwa.rw/rw/body/list/all?utf8=%E2%9C%93&public_body_query=city+of&commit=Shaka
  * HTTP Method: GET
  * Parameters : {"utf8"=>"✓", "public_body_query"=>"city of", "commit"=>"Shaka", "controller"=>"public_body", "action"=>"list", "locale"=>"rw"}
  * Timestamp  : 2020-09-22 18:52:53 +0200
  * Server : mastodon
    * Rails root : /data/vhost/rwanda.alaveteli.org/alaveteli-2020-09-22T15-07-36
  * Process: 4621

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"REDACTED", "locale"=>"rw"}

-------------------------------
Backtrace:
-------------------------------

  lib/i18n_fixes.rb:35:in `block in gettext_interpolate'
  lib/i18n_fixes.rb:31:in `gsub'
  lib/i18n_fixes.rb:31:in `gettext_interpolate'
  lib/i18n_fixes.rb:22:in `n_'
  app/controllers/public_body_controller.rb:133:in `block in list'
  lib/alaveteli_localization.rb:46:in `with_locale'
  app/controllers/public_body_controller.rb:125:in `list'
  app/controllers/application_controller.rb:116:in `record_memory'
  lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by gbp** [comment]
Fixed https://www.transifex.com/mysociety/alaveteli/translate/#rw/apppot/92362979 will need to do a translation hotfix

**Comment by gbp** [comment]
This has now been deployed
