### ISSUE TITLE
[ERROR] followups#new (ActionView::Template::Error) "undefined method `help_page_url' 

### ISSUE THREAD

**Issue by garethrees** [mysociety/sobanukirwa-theme#94]
```
An ActionView::Template::Error occurred in followups#new:

undefined method `help_page_url' for #<#<Class:0x00007fbc72d65480>:0x00007fbc6de48708>
Did you mean? help_api_url
help_pro_url
pro_page_url
lib/themes/sobanukirwa-theme/lib/views/help/_why_they_should_reply_by_email.html.erb:1:in `_lib_themes_sobanukirwa_theme_lib_views_help__why_they_should_reply_by_email_html_erb__581551792518184117_70223637191120'


-------------------------------
Request:
-------------------------------

* URL : https://sobanukirwa.rw/request/468/followups/new/354?gone_postal=1
* HTTP Method: GET
* Parameters : {"gone_postal"=>"1", "controller"=>"followups", "action"=>"new", "request_id"=>"468", "incoming_message_id"=>"354"}
* Timestamp : 2020-10-13 23:37:08 +0200
* Rails root : /data/vhost/rwanda.alaveteli.org/alaveteli-2020-10-12T15-32-50

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en_RW",
"user_id"=>1339,
"ttl"=>"2020-10-13T23:37:08.261+02:00",
"remember_me"=>false,
"post_redirect_token"=>"j9x97oo3qxwy89h9hir",
"_csrf_token"=>"REDACTED"}


-------------------------------
Backtrace:
-------------------------------

lib/themes/sobanukirwa-theme/lib/views/help/_why_they_should_reply_by_email.html.erb:1:in `_lib_themes_sobanukirwa_theme_lib_views_help__why_they_should_reply_by_email_html_erb__581551792518184117_70223637191120'
app/views/followups/new.html.erb:21:in `_app_views_followups_new_html_erb__3049512818911445349_70223678615480'
app/controllers/application_controller.rb:118:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by gbp** [comment]
Fixed in d169d5d3342653b644150dd582943dfc4c68d747
